name = "usa" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "cv.shopee.sg.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "cvs-deo.shopeemobile.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "blog.clova.line.me.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "bimbel.ruangguru.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "sogood.linefriends.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "chat.xl.co.id.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "link.e.tiktok.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "space.byu.id.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "go2.webtoon.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "udemy.com.indo.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "beta.zoom.us.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "platform.opensignal.com.us.nurisfamz.my.id"
custom_domain = true
[[routes]]
pattern = "care.pamg.naver.com.us.nurisfamz.my.id"
custom_domain = true


[vars]
# UUID = "74f9da00-cdf1-4612-916c-fdab0ad8179c"
# PROXYIP = "8.219.97.248"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "3e96e615-9cd6-4acb-ae79-1318a28e0626"
